name = "Dream Plus"
license = "MIT"
licenselink = "https://github.com/ShaunaGordon/hugo-dream-plus/blob/master/LICENSE"
description = "An upgraded version of the hugo-dream-theme and hugo-dream-plus theme with tons of new features."
homepage = "https://github.com/ShaunaGordon/hugo-dream-plus"
tags = ["clean", "blog", "single page", "responsive", "google analytics","disqus", "personal", "syntax highlighting", "single page", "mobile", "light", "dark"]
features = ["randomBackground","favicon","blurBackground","home cards","flip", "colorful", "imagebackground", "i18n", "copyright", "motto", "darkMode", "themeSwitchable"]
min_version = "0.55"

authors = [
	{name = "Utkarsh Verma", homepage = "https://utkarshverma.github.io"},
	{name = "Shauna Gordon", homepage = "https://shaunagordon.com"}
]

[original]
	name = "UtkarshVerma's Blog"
	homepage = "https://utkarshverma.github.io"
	repo = "https://github.com/UtkarshVerma/utkarshverma.github.io"
