baseURL = "https://dream-plus-posts.netlify.com"
title = "ShaunaGordon's Blog"
paginate = 4
enableRobotsTXT = true

#Skip building these files
ignoreFiles = ["content/404.md", "content/about.md", "content/cards/\\.*"]

#Syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

#Enable Hugo Emoji Conversion
enableEmoji=true

[module]
	[[module.imports]]
		path = "github.com/ShaunaGordon/hugo-dream-plus"

[params]
	#Favicon for site
	favicon = "/img/defaultFav.ico"

	#Set whether you're hosting "cards" or "post"
	contentType = "posts"

	siteStartYear = 2018

	[params.author]
		name = "Shauna Gordon"
		description = "Just a random blog for random stuff, mostly tech-related."
		avatar = "https://shaunagordon.com/images/avatar.png"
		motto = "I make things."

	[params.features]
		#Enable Twitter Emoji
		twitterEmoji = true
		#Enable Table of Contents
		toc = true
		#Enable share card
		shareCard = true
		#Use custom CSS
		customCSS = []

	#Tags settings
	[params.tags]
		enabled = true

	#Categories settings
	[params.categories]
		enabled = true

	#Series settings
	[params.series]
		enabled = true

[taxonomies]
	category = "categories"
	tag = "tags"
	series = "series"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[social]
	email = "shauna@gordons.me"
	github = "ShaunaGordon"
	gitlab = "shauna"
	resume = "//resume.shaunagordon.com"
	buymecoffee = "//shaunagordon.com#buy-me-coffee"
	# stackoverflow = ""
	# medium = ""
	# twitter = ""

[services]
	[services.disqus]
		shortname = ""
	[services.googleAnalytics]
		id = ""
